export const TOPICS = {
  API: 'API',
  BCK: 'Backend',
  CHR: 'Charting',
  CLI: 'CLI',
  CLT: 'Client',
  CSS: 'CSS',
  DTL: 'Data Layer',
  DTB: 'Database',
  DVO: 'DevOps',
  DVT: 'DevTool',
  FRM: 'Framework',
  FRT: 'Frontend',
  GEN: 'Generator',
  LNG: 'Language',
  SEC: 'Security',
  SFT: 'Software',
  TMP: 'Templating',
  TST: 'Testing',
  UTL: 'Utility',
  WEB: 'Web',
};
